//go:build windows

package ddsm

import (
	"fmt"
	"sort"
	"strings"
)

// renderWindowsStartScript materializes a per-slot start.ps1. The Linux
// equivalent is the embedded bash defaultStartScript in server.go.
//
// Contract: env vars passed in (PORT, MAP, SERVER_PASSWORD) are baked into
// the script as literal values rather than $env: lookups, because the
// process is spawned by DDSM-the-CLI which does not propagate arbitrary
// environment. RCON password matches the Linux build (ddsm_rcon_secret).
//
// volumePath is the slot root (Cfg.ServersDir/<id>); the game tree lives
// at <volumePath>/Deadlock/.
func renderWindowsStartScript(volumePath string, port int, env map[string]string) string {
	mapName := env["MAP"]
	if mapName == "" {
		mapName = "dl_streets"
	}
	password := env["SERVER_PASSWORD"]

	// Stable iteration of any extra env keys for reproducibility.
	keys := make([]string, 0, len(env))
	for k := range env {
		if k == "MAP" || k == "PORT" || k == "SERVER_PASSWORD" {
			continue
		}
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var extraEnv strings.Builder
	for _, k := range keys {
		v := strings.ReplaceAll(env[k], `"`, `\"`)
		fmt.Fprintf(&extraEnv, "$env:%s = \"%s\"\n", k, v)
	}

	pwLine := ""
	if password != "" {
		safe := strings.ReplaceAll(password, `"`, `\"`)
		pwLine = fmt.Sprintf("$ARGS += \"+sv_password\", \"%s\"\n", safe)
	}

	// Native Windows PowerShell start script. Forward slashes are fine in
	// PowerShell paths.
	return fmt.Sprintf(`# Generated by DDSM Windows backend - do not edit
$ErrorActionPreference = "Stop"
$VOLUME = "%s"
$DEADLOCK_DIR = Join-Path $VOLUME "Deadlock"
$DEADWORKS_EXE = Join-Path $DEADLOCK_DIR "game\bin\win64\deadworks.exe"
$DEADLOCK_EXE = Join-Path $DEADLOCK_DIR "game\bin\win64\deadlock.exe"

%s
$EXE = if (Test-Path $DEADWORKS_EXE) { $DEADWORKS_EXE } else { $DEADLOCK_EXE }
if (-not (Test-Path $EXE)) {
    Write-Error "Server binary not found at $EXE"
    exit 1
}

$ARGS = @(
    "-dedicated",
    "-usercon",
    "-insecure",
    "-ip", "0.0.0.0",
    "-convars_visible_by_default",
    "-allow_no_lobby_connect",
    "-novid",
    "-port", "%d",
    "+map", "%s",
    "+rcon_password", "ddsm_rcon_secret",
    "+sv_cheats", "0",
    "+tv_enable", "0",
    "+citadel_upload_replay_enabled", "0",
    "+tv_citadel_auto_record", "0",
    "+spec_replay_enable", "0",
    "+fps_max", "30",
    "-width", "640",
    "-height", "480",
    "-nojoy"
)
%s
$LogPath = Join-Path $DEADLOCK_DIR "dspawn.log"
Set-Location (Split-Path $EXE -Parent)
"=== ddsm start $(Get-Date -Format o) port=%d map=%s exe=$EXE ===" | Out-File -Append -FilePath $LogPath
& $EXE @ARGS 2>&1 | Tee-Object -FilePath $LogPath -Append
`, volumePath, extraEnv.String(), port, mapName, pwLine, port, mapName)
}
